### ISSUE TITLE
Broken link to 'Array Model' in Day 6

### ISSUE THREAD

**Issue by Janiczek** [rikedyp/APLWorkshop#4]
Hello! 
First of all I want to thank you for the workshop. I'm learning a ton about APL this way.

I just want to raise the issue that I've arrived at [day 6](https://rikedyp.uk/APLWorkshop/course/6) and there is a broken link:
https://rikedyp.uk/APLWorkshop/course/day1/arraymodel

It would have come really handy at that point, because I didn't get most of how the rank operator works just from fiddling with the examples :slightly_smiling_face:

**Comment by hashslingrz** [comment]
Hey, thanks for the tip Martin! Richard has put a lot of hard work into this project, so I'm sure he'd be glad to hear that.

The link should be: https://rikedyp.uk/APLWorkshop/course/arraymodel

The structure of the Workshop has been shifted around a few times while we figure out how to use GitHub Pages & Jekyll to their fullest. Unfortunately, that means sometimes little things fall through the cracks. Thanks again. :smile:

**Comment by rikedyp** [comment]
Also now seeing that The Array Model page is a bit incomplete - I'll move it up my todo list
